---
ansible_mode: "True"
satmode: "True"
zip_log: "$False"
account: "{{ account_name | default('SDE') }}"
blueid: "{{ hwsw_blueid_bac_id | default('BAC9999999') }}"
chipid: "MyChip"
location: "{{ country | default('Kyndryl') }}"
sqlinstance: "all"
check_list: ['all']
udcmode: "True"
